'use client';

import React, { useState, useEffect, useRef } from 'react';
import { FaWhatsapp, FaCopy, FaMagic, FaCheck, FaTimes, FaSpinner } from 'react-icons/fa';

interface Lead {
  id: string;
  empresa: string;
  website: string;
  telefono: string;
  guion: string;
  raw_data: string;
}

interface GuionModalProps {
  lead: Lead;
  isOpen: boolean;
  onClose: () => void;
  onSaved: () => void;
  getWhatsAppLink: (lead: Lead, guion: string) => string;
}

export default function GuionModal({ lead, isOpen, onClose, onSaved, getWhatsAppLink }: GuionModalProps) {
  const [guion, setGuion] = useState('');
  const [perfil, setPerfil] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [editing, setEditing] = useState(false);
  const hasAutoGenerated = useRef(false);

  // Extraer datos existentes
  useEffect(() => {
    if (!isOpen) return;
    setGuion(lead.guion || '');
    setPerfil('');
    setError('');
    setEditing(false);
    hasAutoGenerated.current = false;

    if (lead.raw_data) {
      try {
        const raw = JSON.parse(lead.raw_data);
        if (raw.perfil_ia) setPerfil(raw.perfil_ia);
      } catch {}
    }
  }, [isOpen, lead.id]);

  // Auto-generar si no tiene guion
  useEffect(() => {
    if (!isOpen || lead.guion || hasAutoGenerated.current) return;
    hasAutoGenerated.current = true;
    handleGenerate();
  }, [isOpen, lead.guion]);

  const handleGenerate = async () => {
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/leads/generar-guion', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ lead_id: lead.id })
      });
      const data = await res.json();
      if (data.success) {
        setGuion(data.guion);
        setPerfil(data.perfil || '');
        setEditing(false);
        onSaved();
      } else {
        setError(data.error || 'Error al generar el guion');
      }
    } catch {
      setError('Error de red. ¿Está corriendo el servidor?');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(guion);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSaveEdit = async () => {
    try {
      const res = await fetch('/api/leads/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: lead.id, guion })
      });
      if (res.ok) {
        setEditing(false);
        onSaved();
      } else {
        setError('Error al guardar');
      }
    } catch {
      setError('Error de red al guardar');
    }
  };

  if (!isOpen) return null;

  const wapLink = lead.telefono ? getWhatsAppLink(lead, guion) : '#';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm" onClick={onClose}>
      <div className="bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl w-full max-w-lg mx-4 max-h-[90vh] overflow-y-auto" onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between p-6 border-b border-slate-800">
          <div>
            <h3 className="text-lg font-bold text-white">{lead.empresa}</h3>
            {lead.website && (
              <a href={lead.website.startsWith('http') ? lead.website : `https://${lead.website}`} target="_blank" rel="noopener noreferrer" className="text-xs text-amber-500 hover:text-amber-400">{lead.website}</a>
            )}
          </div>
          <button onClick={onClose} className="text-slate-500 hover:text-white text-xl"><FaTimes /></button>
        </div>

        <div className="p-6 space-y-5">
          {/* Loading */}
          {loading && (
            <div className="flex flex-col items-center justify-center py-8 space-y-3">
              <FaSpinner className="text-amber-500 text-2xl animate-spin" />
              <p className="text-sm text-slate-400">Analizando {lead.empresa}...</p>
            </div>
          )}

          {/* Perfil */}
          {!loading && perfil && (
            <div className="bg-slate-800 rounded-xl p-4 border border-slate-700">
              <p className="text-[10px] text-slate-500 uppercase font-bold mb-1">Qué hace esta empresa</p>
              <p className="text-sm text-slate-300 leading-relaxed">{perfil}</p>
            </div>
          )}

          {/* Guion */}
          {!loading && guion && (
            <div>
              <div className="flex items-center justify-between mb-2">
                <p className="text-[10px] text-slate-500 uppercase font-bold">Mensaje WhatsApp</p>
                {!editing && <button onClick={() => setEditing(true)} className="text-xs text-slate-500 hover:text-amber-400">Editar</button>}
              </div>
              {editing ? (
                <div className="space-y-3">
                  <textarea value={guion} onChange={e => setGuion(e.target.value)} rows={5}
                    className="w-full bg-slate-800 border border-slate-700 text-white rounded-xl p-3 text-sm outline-none focus:border-amber-500 resize-none" autoFocus />
                  <div className="flex gap-2 justify-end">
                    <button onClick={() => { setGuion(lead.guion); setEditing(false); }} className="px-3 py-1.5 text-xs text-slate-400 hover:text-white">Cancelar</button>
                    <button onClick={handleSaveEdit} className="px-3 py-1.5 text-xs bg-amber-600 hover:bg-amber-500 text-white rounded-lg font-bold">Guardar</button>
                  </div>
                </div>
              ) : (
                <div className="bg-emerald-950/30 border border-emerald-900/50 rounded-xl p-4">
                  <p className="text-sm text-emerald-100 leading-relaxed whitespace-pre-wrap">{guion}</p>
                </div>
              )}
            </div>
          )}

          {/* Error */}
          {!loading && error && (
            <div className="bg-red-950/30 border border-red-900/50 rounded-xl p-4">
              <p className="text-xs text-red-400">{error}</p>
              <button onClick={handleGenerate} className="mt-2 text-xs text-red-400 hover:text-red-300 underline">Reintentar</button>
            </div>
          )}

          {/* Acciones */}
          {!loading && guion && (
            <div className="flex justify-between items-center pt-2 border-t border-slate-800">
              <button onClick={handleGenerate} disabled={loading}
                className="flex items-center gap-2 bg-purple-600/20 hover:bg-purple-600/30 text-purple-400 font-bold py-2 px-4 rounded-xl text-xs border border-purple-600/30 transition-all disabled:opacity-50">
                <FaMagic className="text-xs" /> Regenerar
              </button>
              <div className="flex gap-2">
                <button onClick={handleCopy}
                  className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold py-2 px-3 rounded-xl text-xs border border-slate-700 transition-all">
                  {copied ? <FaCheck className="text-emerald-400" /> : <FaCopy className="text-xs" />}
                  {copied ? 'Copiado' : 'Copiar'}
                </button>
                {lead.telefono && (
                  <a href={wapLink} target="_blank" rel="noopener noreferrer"
                    className="flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold py-2 px-4 rounded-xl text-xs shadow-lg transition-all">
                    <FaWhatsapp /> Enviar
                  </a>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
